<a href="https://colab.research.google.com/github/NiliS2006/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

In [29]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [30]:
print(array[0])
print(array[1])
print(array[2])
print(array[3])
print(array[4])

1
2
3
4
5


In [31]:
array[:]

array([1, 2, 3, 4, 5])

In [32]:
array[:3]

array([1, 2, 3])

In [33]:
array[3:]

array([4, 5])

In [34]:
array.ndim

1

In [35]:
array.size

5

In [36]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a[2:4]

array([[7, 8, 9]])

In [38]:
a.ndim

2

In [39]:
a.size

9

In [50]:
arr = np.array([77,34,52,21,5])
arr

array([77, 34, 52, 21,  5])

In [54]:
arr1 =np.sort(arr)
arr1

array([ 5, 21, 34, 52, 77])

In [56]:
np.concatenate((arr1,arr))

array([ 5, 21, 34, 52, 77, 77, 34, 52, 21,  5])

In [61]:
x = np.array(([1,2],[3,4]))
y = np.array(([5,6],[7,8]))
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
arrays = x.reshape(2,2)
arrays

array([[1, 2],
       [3, 4]])

In [66]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [67]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [71]:
print(np.arange(20).reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [79]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(array[array < 15])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [80]:
print(array[array >=15])

[15 16 17 18 19 20]


In [82]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [83]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [84]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [92]:
array=np.array([1,2,3,4,5,6,7,8,9])
np.hsplit(array,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [93]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.vsplit(array,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [95]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr.shape

(3, 5)

In [97]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
array=np.array([[5,4,3,2,1],[10,9,8,7,6],[15,14,13,12,11]])
np.tile(arr,(4,5))

array([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,
         2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,
         7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11,
        12, 13, 14, 15, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,
         2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,
         7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11,
        12, 13, 14, 15, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,  2,  3,  4,  5,  1,
         2,  3,  4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  6,
         7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 

In [99]:
arrays = np.hstack((arr,array))
arrays

array([[ 1,  2,  3,  4,  5,  5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10, 10,  9,  8,  7,  6],
       [11, 12, 13, 14, 15, 15, 14, 13, 12, 11]])

In [100]:
np.tile(arrays,(2,2))

array([[ 1,  2,  3,  4,  5,  5,  4,  3,  2,  1,  1,  2,  3,  4,  5,  5,
         4,  3,  2,  1],
       [ 6,  7,  8,  9, 10, 10,  9,  8,  7,  6,  6,  7,  8,  9, 10, 10,
         9,  8,  7,  6],
       [11, 12, 13, 14, 15, 15, 14, 13, 12, 11, 11, 12, 13, 14, 15, 15,
        14, 13, 12, 11],
       [ 1,  2,  3,  4,  5,  5,  4,  3,  2,  1,  1,  2,  3,  4,  5,  5,
         4,  3,  2,  1],
       [ 6,  7,  8,  9, 10, 10,  9,  8,  7,  6,  6,  7,  8,  9, 10, 10,
         9,  8,  7,  6],
       [11, 12, 13, 14, 15, 15, 14, 13, 12, 11, 11, 12, 13, 14, 15, 15,
        14, 13, 12, 11]])